version: '3.1'
services:
  user-management-app:
    container_name: user-management-app
    image: user-management-app
    ports:
      - "8081:8081"
    depends_on:
      - postgresqluser
  postgresqluser:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=usermanagementdb