version: '3.1'
services:
  group-management-app:
    container_name: group-management-app
    image: group-management-app
    ports:
      - "8082:8082"
    depends_on:
      - postgresqlgroup
  postgresqlgroup:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=groupmanagementdb